# action.yml
name: 'Hello World -- miguelemosreverte'
branding:
  icon: "airplay"
  color: "gray-dark"
description: 'Greet someone and record the time'
inputs:
  subcommand:  
    description: 'bundle|join|lint|preview-docs|push|split|stats'
    required: true
    default: 'lint'
  file:  # id of input
    description: 'openapi file'
    required: true
    default: 'openapi.json'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subcommand }}  ${{ inputs.file }}